name: Build on Windows

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: windows
        run: |
          pushd C:\
          aria2c -x4 -s4 https://github.com/skeeto/w64devkit/releases/download/v2.5.0/w64devkit-x64-2.5.0.7z.exe
          7z x w64devkit-x64-2.5.0.7z.exe
          git clone -b wfm-custom https://github.com/Waim908/wfm.git
          cd wfm
          build.bat
          dir

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: wfm
          draft: false
          prerelease: false
          tag_name: wfm
          body: |
            wfm test
          files: |
            C:\wfm\wfm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}