name: Build on Windows

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      inputTag:
        description: "Tag："
        required: true
        default: "1.5b1"

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: windows
        # default powershell
        run: |
          pushd C:\
          aria2c -x4 -s4 https://github.com/skeeto/w64devkit/releases/download/v2.5.0/w64devkit-x64-2.5.0.7z.exe
          7z x w64devkit-x64-2.5.0.7z.exe
          git clone -b wfm-custom https://github.com/Waim908/wfm.git wfm-src
          cd wfm-src
          .\build_action.bat
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          mkdir C:\wfm
          cp wfm.exe C:\wfm\
          cp libcdio.dll C:\wfm\
          cd C:\
          7z a wfm.zip wfm
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: wfm
          draft: false
          prerelease: false
          tag_name: ${{ github.event.inputs.inputTag }}
          body: |
            wfm test
          files: |
            C:\wfm.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}